apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
  labels:
    app: backend-api 
spec:
  type: LoadBalancer
  selector:
    app: backend-api 
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000 

