apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: grownpossum
spec:
  type: LoadBalancer
  selector:
    app: grownpossum
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

