# backend-api/k8s/backend-api-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-api-service
spec:
  selector:
    app: backend-api
  ports:
    - protocol: TCP
      port: 80            # Port the service exposes (on the Node VM)
      targetPort: 5000    # Port your Flask app listens on (in the container)
  type: ClusterIP         # Change to LoadBalancer if you want external access

